import Link from 'next/link';
import type { ReactNode } from 'react';
import { PageHeader } from '@/components/bench/PageHeader';
import pageStyles from '@/components/bench/page.module.css';
import { OrderTrack } from '@/components/OrderTrack/OrderTrack';
import { Panel } from '@/components/Panel/Panel';
import { StatNumber } from '@/components/StatNumber/StatNumber';
import { listPurchaseOrders, type PurchaseOrderListRow } from '@/lib/purchase-orders/queries';
import {
  committedValue,
  fmtDate,
  fmtMoney,
  isOpenPo,
  openPoCount,
  poStatusLabel,
} from '@/lib/purchase-orders/transform';
import { createSupabaseServer } from '@/lib/supabase/server';
import { OrderChain } from './OrderChain';
import styles from './purchase-orders.module.css';

export const metadata = { title: 'Purchase Orders · The Chain' };

/**
 * Purchase Orders — the procurement cockpit (Block 6, Wave 6.3-A). Server
 * Component: RLS-scoped POs imported from QuickBooks (and, later, generated by
 * the reorder engine). The featured order renders as the full igniting chain;
 * the ledger below carries every order with its compact progress track.
 */
export default async function PurchaseOrdersPage(): Promise<ReactNode> {
  const supabase = await createSupabaseServer();
  const rows = await listPurchaseOrders(supabase);

  if (rows.length === 0) {
    return (
      <div className={pageStyles.stack}>
        <PageHeader eyebrow="Procurement · orders in flight" title="Purchase Orders" />
        <Panel prefix="Orders" title="No purchase orders yet">
          <div className={styles.connect}>
            <p className={styles.connectCopy}>
              Connect QuickBooks and run a sync to pull your open purchase orders into the chain.
              Each order arrives with its supplier, lines, and delivery date, ready to watch
              advance.
            </p>
            <Link href="/integrations/quickbooks" className={pageStyles.cta}>
              Connect QuickBooks
            </Link>
          </div>
        </Panel>
      </div>
    );
  }

  const featured = rows.find((r) => isOpenPo(r.status)) ?? rows[0];

  return (
    <div className={pageStyles.stack}>
      <PageHeader eyebrow="Procurement · orders in flight" title="Purchase Orders" />

      <div className={styles.metrics}>
        <div className={styles.metric}>
          <span className={styles.metricKey}>Open orders</span>
          <StatNumber value={openPoCount(rows)} size="panel" />
        </div>
        <div className={styles.metric}>
          <span className={styles.metricKey}>Committed</span>
          <StatNumber
            value={fmtMoney(committedValue(rows))}
            unit="$"
            unitPosition="prefix"
            size="panel"
          />
        </div>
        <div className={styles.metric}>
          <span className={styles.metricKey}>Total orders</span>
          <StatNumber value={rows.length} size="panel" />
        </div>
      </div>

      {featured ? <FeaturedOrder po={featured} /> : null}

      <div className={styles.ledger}>
        <div className={styles.head} aria-hidden="true">
          <span>Order</span>
          <span>Supplier</span>
          <span>Progress</span>
          <span className={styles.numHead}>Lines</span>
          <span className={styles.numHead}>Total</span>
          <span className={styles.numHead}>Due</span>
          <span>Status</span>
        </div>
        {rows.map((row) => (
          <OrderRow key={row.id} row={row} />
        ))}
      </div>
    </div>
  );
}

function FeaturedOrder({ po }: { po: PurchaseOrderListRow }): ReactNode {
  return (
    <section className={styles.hero} aria-label={`Featured order ${po.reference}`}>
      <div className={styles.heroHead}>
        <span className={styles.heroEyebrow}>
          {isOpenPo(po.status) ? 'Latest open order' : 'Latest order'}
        </span>
        <span className={styles.heroMeta}>
          {po.reference} · {po.lineCount} {po.lineCount === 1 ? 'line' : 'lines'}
          {po.total != null ? ` · $${fmtMoney(po.total)}` : ''}
        </span>
      </div>
      <OrderChain po={po} />
    </section>
  );
}

function OrderRow({ row }: { row: PurchaseOrderListRow }): ReactNode {
  return (
    <Link
      href={`/suppliers/${row.supplierId}`}
      className={styles.row}
      aria-label={`${row.reference} from ${row.supplierName}`}
    >
      <span className={styles.cellRef}>{row.reference}</span>
      <span className={styles.cellSupplier}>{row.supplierName}</span>
      <span className={styles.cellTrack}>
        <OrderTrack po={row} />
      </span>
      <span className={styles.cellNum}>
        <StatNumber value={row.lineCount} />
      </span>
      <span className={styles.cellNum}>
        <StatNumber
          value={row.total == null ? null : fmtMoney(row.total)}
          unit="$"
          unitPosition="prefix"
        />
      </span>
      <span className={styles.cellNum}>
        <StatNumber value={row.expectedDeliveryAt ? fmtDate(row.expectedDeliveryAt) : null} />
      </span>
      <span className={styles.cellStatus}>
        <StatusTag row={row} />
      </span>
    </Link>
  );
}

function StatusTag({ row }: { row: PurchaseOrderListRow }): ReactNode {
  const cls =
    row.status === 'canceled'
      ? styles.statusCanceled
      : isOpenPo(row.status)
        ? styles.statusOpen
        : styles.statusDone;
  return (
    <span className={`${styles.statusTag} ${cls}`}>
      <span className={styles.statusDot} aria-hidden="true" />
      {poStatusLabel(row.status)}
    </span>
  );
}
